steps:
- input: Task Name
  fields:
    - select: Task Name
      hint: The name of thes task to retry. Defaults to all tasks.
      default: all
      key: task-name
      options:
        - label: All
          value: all
        - label: Sync Lead to Salesforce
          value: sync_lead
        - label: Convert Lead in Salesforce
          value: convert_lead
        - label: Unquarantine Lead in Salesforce
          value: unquarantine
        - label: Import Lead into Klondike
          value: import_lead
        - label: Change Degree Offering
          value: change_offering
        - label: Upsert Lead from Salesforce
          value: upsert_lead

- wait

- label: "Generating Job Pipeline"
  command: "./buildkite/retry-failed/generate-job-pipeline.sh | buildkite-agent pipeline upload"
