steps:
  - label: ":construction_worker: Build"
  - command: exit 1
    key: "step1"
  - wait: ~
    continue_on_failure: true
  - command: |
      if [ $(buildkite-agent step get "outcome" --step "step1") != "passed" ]; then
         cat <<- YAML | buildkite-agent pipeline upload 
         steps:
           - label: "Notify email about soft failed step"
             command: echo "Notifying micheal about the failed step"
         notify:
            - email: "micheal.obasa@buildkite.com"

                  
      YAML
      fi


