steps:
  - commands: 
    - echo "test this"
      buildkite-agent artifact upload "build.log"
      cat << EOF | buildkite-agent annotate --style "info"
      EOF
    artifact_paths: "build.log"






