steps:
  - label: "Echo Name"
    command: ec
    notify:
       - github_commit_status:
           context: "my-custom-status-1"
       - github_commit_status:
           context: "my-custom-status-2" 

