steps:
  - label: "Echo Name"
    command: echo "Hello, Buildkites!"
    notify:
       - github_commit_status:
           context: "Passed"
           if: build.state == "passed"
       - github_commit_status:
           context: "fail"
           if: build.state != "failing"
